### ISSUE TITLE
Trouble with find device

### ISSUE THREAD

**Issue by S-Kerrigan** [Walkman100/GPMplaylistDL#1]
Hello!
I have Python v3.x, also "requests &  gmusicapi". Have subscription on youtube. Created "password to application". Setup fields (login/password) in script done.
However, i have successful login, but after that, script give me "No Android or iOS device linked to account!"
My phone, of course, associated with my G-Account. What's i do wrong?

UPD:
Custom string in script "print("DEV"+device['type'])" give me only one result: DEVDESKTOP_APP

**Comment by Walkman100** [comment]
Hi, didn't see your issue (haven't been on GH in a while), the Google Play Music API requires you have an android (or iOS) device associated. You'll need to download the Google Play Music app and connect that to your account, however I'm not sure if the subscription on YouTube gives you access to Google Play Music itself...

**Comment by Walkman100** [comment]
Yeah, in the README:

> Please note that this will ONLY work if you have a subscription, and a mobile device associated with your account.
